name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [ opened, reopened, ready_for_review, synchronize ]

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  NODE_CONFIG_ENV: "test"

jobs:
  install_packages:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft == false
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'  
      - uses: bahmutov/npm-install@v1
      - name: Install yarn dependencies          
        run: yarn install --prefer-offline  
      - name: see what's in folder
        run: pwd;ls -al

  unit-tests-server:
    runs-on: ubuntu-latest
    needs: install_packages
    if: github.event.pull_request.draft == false
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'    
      - uses: bahmutov/npm-install@v1
      - name: Install yarn dependencies          
        run: yarn install --prefer-offline  
      # - name: add binary folder to path
      #   run: echo "$PWD/node_modules/.bin" >> $GITHUB_PATH
      - name: see what's in folder
        run: pwd;ls -al
      - name: what is my PATH
        run: echo $PATH
      - name: see what's in node_modules folder
        run: ls -al ./node_modules        
      - name: check jest runs 
        run: jest --version
      - name: check next runs 
        run: next --version        
      - name: check tsc runs 
        run: tsc --version                
      - name: check tslint runs 
        run: tslint --version                